### ISSUE TITLE
Finalise the options that initial launch will have

### ISSUE THREAD

**Issue by kiriappeee** [hiraash/islamify#3]
Right now I'm thinking that the initial product will have, 
- Homepage to view a stream of submissions.
  - Categorization can come later.
- User accounts
  - Users can upload submissions 
    - Do we manually verify at the start?
- Play audio streams
  - Can stream
  - Audio files can be arranged to play in 'series': part 1, 2, 3..
  - Can download to play on the go (?)

**Comment by hiraash** [comment]
Sorry I hadn't noticed the issues. I will add you as a collaborator and will also nail down the MVP plan at a high-level.

**Comment by hiraash** [comment]
Added two pages to the wiki. Lets continue the convo there. This this particular one.
https://github.com/hiraash/islamify/wiki/Project-Plan,-Web---MVP
